name: 'Future Self backend'
services:
  future-self-backend:
    image: ghcr.io/ibsule/future-self-backend:latest
    container_name: future-self-backend-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5010:5001