name: 'Futureself'
services:
  futureself-backend:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: futureself-api
    restart: unless-stopped
    env_file: .env
    ports:
      - 5010:5001
  
  futureself-web:
    build: 
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: futureself-web
    restart: unless-stopped
    env_file: .env
    ports:
      - 8010:5173
  
  postgresdb:
    image: postgres:18.3
    container_name: futureself-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: please-change-me-M2ncjemKrtsVBrTuho
      POSTGRES_DB: futureself
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:8.6
    container_name: futureself-redis
    command: redis-server --requirepass please-change-me-GWLq7kqLcWhEkVoZ
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pg_data: